config/routes.rb
Nomster::Application.routes.draw do
  devise_for :users

  root 'places#index'

  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end

  resources :users, only: :show
  resources :comments, only: :destroy
  resources :photos, only: :destroy
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email


  RATINGS = {
    'one star'    => '1_star',
    'two stars'   => '2_stars',
    'three stars' => '3_stars',
    'four stars'  => '4_stars',
    'five stars'  => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver
  end
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  mount_uploader :picture, PictureUploader 
  
  belongs_to :place
  belongs_to :user


end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, :length => { :minimum => 3 }
  validates :address, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    @place = Place.find(params[:place_id])

    # look at this again later, lesson 33.
    @place.comments.create(comment_params.merge(user: current_user)) 

    redirect_to place_path(@place)
    
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @comment.destroy
    
    redirect_to user_path(@comment.user_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])

    # look at this again later, lesson 33.
    @place.photos.create(photo_params)
    #uploader = PictureUploader.new
    #uploader.store!()

    redirect_to place_path(@place)
  end

    def destroy
    @photo = Photo.find(params[:id])

    if @photo.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @photo.destroy
    
    redirect_to user_path(@photo.user_id)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @place = Place.new
  end

  def create
    # devise syntax instead of Place.create()
    @place = current_user.places.create(place_params) 
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit 
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render text: "Not Allowed", status: :forbidden
    end

    @place.update_attributes(place_params)
    
    if @place.valid?
      redirect_to place_path(params[:id])
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
 		@user = User.find(params[:id])
 	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_place_path do %>
              <i class="glyphicon glyphicon-plus-sign"></i>
              New Place
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'slide1.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Delicious!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slide2.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Yum!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slide3.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Lecker!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slide4.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Tasty!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slide5.jpg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Gimme more!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>


<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i class="place_address"><%= place.address %></i><br />
    <p><%= place.description %></p><br />
    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
  
    <!-- Latest comment -->
    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.order("created_at").last.humanized_rating.present? %>
            <b><%= place.comments.order("created_at").last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.order("created_at").last.message %>
          <small><%= place.comments.order("created_at").last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>

<% end %>

<div class="clear"></div>
<br/>
<%= will_paginate @places %>

app/views/places/new.html.erb

<div class="boohyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter your place details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<% if @place.photos.count > 0 %>
  <!-- Slider -->
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">      
    
    <div class="carousel-inner">
      <% active_class = " active"  %>  
      <% if @place.photos %>
        <% @place.photos.each do |photo| %>

          <div class="item <%= active_class %>">
            <%=image_tag photo.picture, class: 'img-responsive' %>
            <% if photo.caption? %>
              <div class="carousel-caption">
                 <%= photo.caption %>
              </div>
            <% end %>
          </div>
          
          <% active_class = "" %>  
        <% end %>
      <% end %>
    </div>

    <!-- Slider Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

  </div>  

  <div class="clear"></div>
  <br/></br>
<% end %>
<div class="booyah-box col-xs-10 col-xs-offset-1">

  <h1><%= @place.name %></h1>
  <i class="place_address"><%= @place.address %></i>
  <p><%= @place.description %></p>
  

  <!-- Google Maps -->
  <% if @place.latitude.present? && @place.longitude.present? %>

    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }

    </script>
    <% 
      if Rails.env == 'development'
        ENV['GOOGLE_MAPS_API_KEY'] = ""
      end
    %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap&key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>"></script>

    <div id="map"></div>

  <% end %>

  <div class="pull-right">
    <% if current_user && current_user == @place.user %>
      <!-- Button trigger modal photos -->
      <button class="btn btn-primary" data-toggle="modal" data-target="#myPhotoModal">Add a photo</button>
      <%= link_to "edit", edit_place_path, class: "btn btn-primary" %>
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>

  <br/><br/>
  <div class="clear"></div>

  
  <!-- Comment Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        </div>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <div class="modal-body">
            <%= f.input :message %>
            <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <br/><br/>

  <!-- Button trigger modal comments -->
  <div class="col-xs-10 col-xs-offset-1">
    <h1 class="pull-left">Comments</h1>
    <!-- Button trigger modal comments -->
    <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
      Add a comment
    </button>
  </div>


  <!-- Add photo modal -->
  <div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
        </div>
        <%= simple_form_for @photo, url: place_photos_path(@place), html: { multipart: true } do |f| %>
          <div class="modal-body">
            <%= f.input :caption %>
            <%= f.input :picture %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <br/><br/>



  <div class="clear"></div>

  <% @place.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-6">
      <blockquote>
        <b><%= comment.humanized_rating  %></b> -
          <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>



</div>


app/views/users/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <div class="col-xs-4">
    <%= image_tag 'user.png' %>
  </div>
  <div class="col-xs-8">
    <h1><%= @user.email %></h1>

    <h3>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>

    <h4><%= @user.comments.count %> total comments</h4>
    <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
  </div>
  <div class="clear"></div>
</div> 
<div class="clear"></div>

<br /><br />
<h1 class="text-center">My Comments</h1>
<br /><br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <% @user.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-12">
      <h2 class=""><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
        <%= link_to "Delete", {:controller => :comments, :action => 'destroy', :id => comment.id}, :class =>"delete_button", :method => 'delete', :confirm => "Are you sure you want to delete this comment?" %>
      </blockquote>
    </div>
  <% end %>

  <div class="clear"></div>
</div>

<div class="clear"></div>
<br /><br />
<h1 class="text-center">My Places</h1>
<br /><br />
<% @user.places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>